### ISSUE TITLE
[BUG] Auto bed leveling freezing

### ISSUE THREAD

**Issue by giorgiomanieri** [CR6Community/Marlin#18]
### Bug Description

When I start the auto bed leveling after the home position, the nozzle moves to first probing and immediately turns back in origin

### My Configurations

Community firmware v1.0.3.6

### Steps to Reproduce

1. Start auto bed leveling from the screen

**Expected behavior:** 

Probing from 1st to 16th point

**Actual behavior:** [What actually happens]

Nozzle stops on first probing

(https://youtu.be/klTeJAVzQS0)

**Comment by Sebazzz** [comment]
Please try to execute G29 from Pronterface and collect logs by activating `M111 S247` first.

**Comment by giorgiomanieri** [comment]
> Please try to execute G29 from Pronterface and collect logs by activating `M111 S247` first.

Where I find the logs then?

**Comment by Sebazzz** [comment]
In the pronterface console

Met vriendelijke groet,
Sebastiaan Dammann
________________________________
Van: giorgiomanieri <notifications@github.com>
Verzonden: Sunday, October 25, 2020 6:54:13 PM
Aan: CR6Community/Marlin <Marlin@noreply.github.com>
CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [CR6Community/Marlin] [BUG] Auto bed leveling freezing (#18)


Please try to execute G29 from Pronterface and collect logs by activating M111 S247 first.

Where I find the logs then?

**Comment by giorgiomanieri** [comment]
> In the pronterface console Met vriendelijke groet, Sebastiaan Dammann
> […](#)
> ________________________________ Van: giorgiomanieri <notifications@github.com> Verzonden: Sunday, October 25, 2020 6:54:13 PM Aan: CR6Community/Marlin <Marlin@noreply.github.com> CC: Sebastiaan Dammann <sebastiaandammann@outlook.com>; Comment <comment@noreply.github.com> Onderwerp: Re: [CR6Community/Marlin] [BUG] Auto bed leveling freezing (#18) Please try to execute G29 from Pronterface and collect logs by activating M111 S247 first. Where I find the logs then? — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCR6Community%2FMarlin%2Fissues%2F18%23issuecomment-716185791&data=04%7C01%7C%7Cb96385fe943640bd7c1808d8790efbf0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637392452540565214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MekHALFQW9h50QRnYHaTNA3sSF9MK9hgeIVkjUufrgc%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAK4FMKRRFIBG3XDO537URDSMRQ4LANCNFSM4S6ONHIA&data=04%7C01%7C%7Cb96385fe943640bd7c1808d8790efbf0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637392452540575209%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=w0kNhVdk2BCVcwkOkAmbZ9RWEG%2BANaxwI0Vre790Wzk%3D&reserved=0>.

I'm sorry, I don't read any log there

**Comment by Sebazzz** [comment]
[firmware-20201025-205250.zip](https://github.com/CR6Community/Marlin/files/5435830/firmware-20201025-205250.zip)

Please try flashing this firmware and try again:

1. Verify flashing with `M115`.
2. Enable debug logging with `M111 S247`
3. Execute G28
4. Execute G29

Also take note of the blue light in the hot-end, when or when not it turns on.

**Comment by giorgiomanieri** [comment]
Log after G29 command:

Recv: Error:Probing Failed
Changing monitoring state from "Operational" to "Error: Probing Failed"
Send: M112
Send: N2 M112*35
Send: N3 M104 T0 S0*34
Send: N4 M140 S0*97
Changing monitoring state from "Error: Probing Failed" to "Offline (Error: Probing Failed)"
Connection closed, closing down monitor

the blue light turns on only near the bed during G28 command

**Comment by Sebazzz** [comment]
Is this the only output you get? I'd expect much more output. Can you post the full output of everything in Pronterface, following the instructions?

**Comment by nickacker** [comment]
More information is required about your current firmware situation @giorgiomanieri. Are you still using 1036? Is this the 1036 build I released or one you've built from the source? Have you attempted to update the firmware to the latest release from this repo?

In the youtube video you linked above, it would appear as though your strain gauge LED is triggered just before it hits the X endstop. The fact that it turns on properly during the home movement tells me that its likely something to do with the bowden/data cable setup you have on it. My guess is that the cable/bowden is pulling the assembly up as it reaches the endstop and therefor, its not able to finish or even start because its already triggered before the optical sensor even.

Remove the data cable saver print, as well as all of the clips youre using to secure the data cable to the bowden tube and try again. Pay very close attention to the blue LED thats under the hotend shroud as it should remain off unless the nozzle is actually pushing on something. If remove the 3d prints from the cables sorts the issue out, then you can certainly go back to using them, but just turn the potentiometer up slightly so accomodate for the uppull on the assembly.

**Comment by nickacker** [comment]
After careful review of the video posted above in the OP. @0:20 seconds, the strain gauge probe is triggered before the X endstop, remains on during the first attempted point, and then turns back off when it resets back to home middle position, indicating that the gauge is working properly. This is expected behavior from a failed first probe and is caused by the strain gauge being activated already before the optical switch.

User to remove the additional clips supporting the data cable and increase resistance to the potentiometer as this is not firmware related.

**Comment by giorgiomanieri** [comment]
Ok. I've tried. It works for now.
Thanks
