### ISSUE TITLE
Feature Request - Randomise Z Home for PEI sheet

### ISSUE THREAD

**Issue by diginfo** [CR6Community/Marlin#238]
I have replaced my glass bed with a PEI magnetic sheet due to the issues related to the yellow surface coating coming off and loosing adhesion for prints, it works very well.

Despite the fact that I have checked the homing force of the strain gauge to be only around 70 grams, eventually the nozzle dents the PEI which may not just be caused by the brass nozzle itself, but also small un-melted filament which as oozed slightly and solidified and gets pressed into the PEI during homing in the centre of the print bed.

So I am thinking that to minimise this, it might be possible to randomise the center Z home position within user-definable area, i.e. a 10mm square ?

So each time it Z- homed it would home randomly within this square thereby minimising the effect of the nozzle pressing and marking the PEI in the exact same time every time.

I realise that this is not for everyone, but it would be a neat work-around to the problem ?!

**Comment by Sebazzz** [comment]
Because this touches the code homing procedures of Marlin, I would like you to ask this at Marlin repository instead: https://github.com/MarlinFirmware/Marlin/issues

I would also suggest to you [to use this start gcode](https://damsteen.nl/blog/2021/02/11/creality-cr6-community-firmware-start-print-without-drooping) to prevent homing hot. That might prevent the issue altogether. I print on PEI too, but I have no issues with my PEI having wear and tear 😉
