### ISSUE TITLE
[FR] TFT Minimal fan speed 

### ISSUE THREAD

**Issue by esunayg** [CR6Community/Marlin#259]
### Is your feature request related to a problem? Please describe.

Most of the time I slice the file at my default/safest settings. But sometimes if the printer can handle I increase the feedrate from tft. After than cooling is not enough and increase fan speed accordingly (for ex: 80%). But every time a layer change or bridge happens slicer changes speed to max but it doesnt go to my TFT fan settings, instead goes to slicer's min setting (fe: 35%). So tft fan setting becomes more like useless, only for vase printing maybe.

### Are you looking for hardware support?

Nope.

### Describe the feature you want

I dont know if it is possible but it would be pretty nice if tft detects that slicer tries to slow down the fan below the settings on tft, it should send gcode to override immediately maybe. Then this setting would be pretty helpful.

**Comment by Sebazzz** [comment]
The TFT doesn't do anything with fan speed, it simply reads the fan speed as set, and tells Marlin to use a different fan speed. This is greatly simplified because it is more complex in reality, but it doesn't sound like a Community Firmware bug or feature to me (as I try to stay clear from core Marlin code).
