### ISSUE TITLE
[BUG] Flow Rate reported 100%, Slicer was set to 97%

### ISSUE THREAD

**Issue by zrdcorp** [CR6Community/Marlin#269]
### Did you test the latest `extui` code or prerelease?

No, there is no prerelease

### Bug Description

I have a v1.1-ERA motherboard.

Installed the correct 4.5.3 version of the 6.1 Community firmware release.
Had to downgrade the Kernel of the TouchScreen  from V4.00 October 2020, to the V3.5 2July 2020 included in the release, otherwise the touchscreen would not work.

I have all the flows in the slicer set to 97%, but while printing the firmware shows 100%.

Is this a Bug? Or does this mean 100% of 97% ???

Same question for feed rate. It shows 100%, is this 100% of the slicer setting??

### Bug Timeline

New on Community Release 6.1

### Expected behavior

Expected the firmware to display the same flow that was set on the slicer.

### Actual behavior

The flow displayed is 100%.

### Steps to Reproduce

Slice at 97% or any other non 100% value.
Print and observe the displayed flow % value.

### Version of CR6Community Firmware

6.1

### Printer model

Creality CR-6 SE

### Motherboard

Creality v1.1.0.0-ERA

### Display

Creality CR-6 stock touch screen

### Mods

Micro Swiss All Metal HotEnd

### Your Slicer

Cura

**Comment by ritchiedc** [comment]
The UI feed and flow percent is the percent of the slicer output. So by your example a UI flow of 100% is 100% of the 97% set in the slicer. The UI and by extension marlin has no knowledge of the slicer settings. It only knows what the slicer ultimately computes for actual speed and extrusion amount when it creates the gcode.

Edit: the feed and flow percentage can be included in the start gcode that is appended to the gcode file. In fact my start gcode includes the commands to set them to 100% so that I don't inadvertently use the values I may have changed during the previous print.
