### ISSUE TITLE
[FR] Display: Remaining printtime 

### ISSUE THREAD

**Issue by DuckAvenger** [CR6Community/Marlin#270]
### Describe the feature you want

Hi

I would be nice if you could add the remaining printtime as informatization on the display.

Thanks

**Comment by ritchiedc** [comment]
The community firmware already does this via M73 messages. This can be configured in both cura 4.9+ or prusaslicer.

**Comment by DuckAvenger** [comment]
Thanks @ritchiedc I found the setting in Cura 

![image](https://user-images.githubusercontent.com/73466970/130348102-db081ae1-302f-41fc-aff7-5f57a1312698.png)

**Comment by ritchiedc** [comment]
Don't know if you noticed but the drop-down that shows M117 in your screen capture, change that to M73. This will put the remaining time underneath the print time instead of in comments in yellow on the screen. Prior to cura 4.9, M117 was the only option which was just a comment to the screen. In 4.9 they implemented the newer M73 specific for reminding time.

**Comment by DuckAvenger** [comment]
Thanks @ritchiedc 

![2021-08-24_07h11_34](https://user-images.githubusercontent.com/73466970/130559648-de3ecf5b-683d-40b8-9218-0e6f125f411e.png)

**Comment by Sebazzz** [comment]
This is already supported: https://damsteen.nl/blog/2021/03/13/estimated-time-remaining-with-the-cr6-community-firmware
