### ISSUE TITLE
[FR] Set custom resolution for auto-leveling

### ISSUE THREAD

**Issue by mxgordon** [CR6Community/Marlin#280]
### Is your feature request related to a problem? Please describe.

My bed may bed a little warped (I'm still trying to figure it out), and there are some points where the nozzle comes Very close to the bed, and others where is it perfect. I believe there may be some "sharper" warps in my bed 

### Describe the feature you want

I want to bed able to set the resolution of the auto-leveling probe manually in the settings. So instead of the default 4x4, I'd like to make it like 10x10 to a better topology of my bed. I have no idea if this is actually possible (there may be hardware limitations I'm not aware of), but if it is, this does sound like a fairly simple feature.

**Comment by jjhu** [comment]
This has been suggested before, but I don't see the point of increasing the grid. Since the code needs to be revised for allowign a bigger grid, as well as UI changes, which is quite some work for a minor/no improvement. 

Hence, there is an option to change your values manually after running ABL. I suggest you make your bed more flush by tuning the eccentric nut and the screws from the bed itself to improve your root problem. 4x4 is plenty enough, with the option to manually change the values.

**Comment by Sebazzz** [comment]
Yes, this is not possible without a touch screen rework. We would need a new page, and dynamically change to the correct page.
Even then, you'd always need to recompile a new Marlin, for yourself only. Sorry - it is not viable.

You can optionally use the 7x7 grid of the CR-6 MAX.
