### ISSUE TITLE
[BUG] Filament change M600 can't recover from 'heater timeout'

### ISSUE THREAD

**Issue by tangcla** [CR6Community/Marlin#58]
The heater change at layer will not reheat the extruder after it has timed out, and the button is blank.
I've attempted this twice with the same issue. 

(Unfortunately both times I was not around to do the filament change in time for it to not timeout.)
![image](https://user-images.githubusercontent.com/8278114/100486212-235ac880-3157-11eb-9c5b-815ab7cc90c0.png)

**Comment by Thinkersbluff** [comment]
I believe M600 is only supported properly if you have an LCD screen, at present.  That is why the filament runout sensor only does a stop SD print right now (M25) and not an M600.

This YouTube video: [https://www.youtube.com/watch?v=6023oBYmXW4](https://www.youtube.com/watch?v=6023oBYmXW4) shows an example of how M600 is set up and used.  You will notice a few events where the LCD Controller menus offer useful functionality that is not available on the touch-screen type of display controller we have on the CR-6 SE.

**Comment by tangcla** [comment]
> I believe M600 is only supported if you have an LCD screen, at present. That is why the filament runout sensor only does a stop SD print right now (M25) and not an M600.

What do you mean by LCD screen (doesn't the CR6SE have one, which is what I took the photo of)?

**Comment by Thinkersbluff** [comment]
No, what the CR-6 has is called a “touch-screen”, in Marlin.  The Ender-3 has an LCD screen, with a controller knob and additional menus.

**Comment by tangcla** [comment]
Does this mean the M600 (also pause at layer height) can't resume?

**Comment by Thinkersbluff** [comment]
> Does this mean the M600 (also pause at layer height) can't resume?

According to this issue record from Marlin, it may be possible to recover from M600 by sending M108:
https://github.com/MarlinFirmware/Marlin/issues/12494

According to these notes on the M108 Break and Continue command:
“With both EMERGENCY_PARSER and HOST_KEEPALIVE_FEATURE enabled, hosts will be able to prompt for continuation or cancellation, confirming with M108 and cancelling with M112.“

The problem seems to be that the M600 command causes the motherboard to ignore commands from the host, while waiting for a response from the controller.  There is a feature called Emergency Parser which should force the motherboard to process a very short list of commands while in that busy state and M108 is one of those.  

At least two other problems complicate this issue on some printers:
1. Emergency Parser is not implemented for all motherboards.  
2. If the message buffer is full, the M108 command may still be ignored.  (That’s why Thinkyhead told that 2018 bug reporter to try M108 several times)

I just successfully used M600 on my CR-6 SE as follows: Start print. Remove filament. Send M600 command from terminal.  Wait fo bed heating to finish and G28 to finish, then printer parked head and beeped for user intervention.  Reinserted filament. Pressed blue bar presented on display (could not see any label on that.) Printer purged a little filament, then resumed print.

I am running the very latest extui from 26 Nov.

It may be worth trying this again, on your system, to understand the limits of what can be done with the limitations we have with a combination of terminal software and touch-screen display.  
If you would like to explore converting the CR-6 SE to an LCD controller, the BTT TFT35 display may be of interest to you.

As to your original BUG, I suggest that the inability of the printer to recover from a heater timeout in this instance may not be a bug so much as a fact.

**Comment by Sebazzz** [comment]
> As to your original BUG, I suggest that the inability of the printer to recover from a heater timeout in this instance may not be a bug so much as a fact.

I believe it is in this case though. The code uses a dialog system for the messages that are passed through the ExtUI API. I suspect something is not entirely right here. But... because in this case heating is involved I think the way it is displayed to the end user needs to be rethought.

I think I'm going to re-implement a bit that will instead:
- Navigate to the print paused screen
- Show the message from Marlin in the M117 line
- The "resume" function would then allow to execute the callback we get from Marlin

**Comment by tangcla** [comment]
I'm not a software guy, but is the blank button on the screen related to the issue? Perhaps it's not linked to a command that the printer is expecting? (or it could just be a lcd firmware thing)

This also happens with the pause on layer command which I tested too. 
![IMG_20201128_125419](https://user-images.githubusercontent.com/8278114/100527033-c3c9ef00-3222-11eb-9ade-2337895cf838.jpg)

**Comment by Sebazzz** [comment]
In my current set-up I'm unable to test this myself. Can you please try the file below? 

If I did it right you should have navigation to the print paused screen. From there you can tap "resume" to follow the filament change procedure. There should also be a temporary indication in the about screen that this file was compiled for this bug.

Please capture any detail you can if it still does not work.

[firmware-20201128-232436.zip](https://github.com/CR6Community/Marlin/files/5611314/firmware-20201128-232436.zip)

**Comment by Thinkersbluff** [comment]
> Please capture any detail you can if it still does not work.

That was scary - I ended up having to reflash to Creality's v2.0.1.2, to recover the use of my printer. :~
Not sure how, but the Feed/Return got "messed-up", such that Feed 100mm gave me ~10mm instead and Return 100mm gave me an initial retraction then a feed of ~20mm more.
I tried flashing back to alpha v4 but that did not correct the problem. Nor did reflashing the display firmware.
I will take a long pause to get my heart rate back down & try going back to alpha v4 tomorrow night. 
Sorry.

**Comment by Sebazzz** [comment]
> Not sure how, but the Feed/Return got "messed-up", such that Feed 100mm gave me ~10mm instead and Return 100mm gave me an initial retraction then a feed of ~20mm more.

That is an unrelated issue @Nushio is working on (the feed screen seems to be a bit off).

**Comment by Sebazzz** [comment]
Also @Github, "should fix" is not the same as "fixes". Stop closing my issues 😄

**Comment by Sebazzz** [comment]
[firmware-20201129-163259.zip](https://github.com/CR6Community/Marlin/files/5612738/firmware-20201129-163259.zip)

This contains some fixes in the feed menu and filament changes (thanks to the testers in the Discord).

**Comment by Thinkersbluff** [comment]
> firmware-20201129-163259.zip

Help! I'm trapped in a "Tune" menu screen, while Octoprint has its way with my printer...

I like having Z offset in the Tune menu, though the box around the current value invites me to tap it to enter a value by keypad, except that nothing happens when I do.
The LED button beeps when I press it, but it still says ON and my LED stays ON.
Back beeps but I can't get back.

I wonder what layer is printing now?...

**Comment by Sebazzz** [comment]
[firmware-20201201-000916.zip](https://github.com/CR6Community/Marlin/files/5619260/firmware-20201201-000916.zip)

Next attempt

**Comment by tangcla** [comment]
> [firmware-20201201-000916.zip](https://github.com/CR6Community/Marlin/files/5619260/firmware-20201201-000916.zip)
> 
> Next attempt
![Uploading IMG_20201201_155112.jpg…]()

**Comment by tangcla** [comment]
> [firmware-20201201-000916.zip](https://github.com/CR6Community/Marlin/files/5619260/firmware-20201201-000916.zip)
> 
> Next attempt

Goes to pause screen, shows holding temperature (200/60) but when I click resume, it shows "heater timeout" and temperature is actually 25/42.
![IMG_20201201_155112](https://user-images.githubusercontent.com/8278114/100698715-430b1e80-33ed-11eb-9b0d-3a1d1df24ef1.jpg)
Also, this firmware version seems to have reset all my settings.

**Comment by Sebazzz** [comment]
Did you try clicking resume again?

**Comment by tangcla** [comment]
Yes, I did.
I left it on purpose so it will drop heat. The screen shows 200/60 degrees the whole time. I pressed resume, then the yellow text showed timeout error, and then it showed the 'correct' temperature.
Pressing resume does nothing (it does not change).

**Comment by tangcla** [comment]
I tested the firmware-20201201-000916.zip version yesterday with a filament change layer. 
As soon as the nozzle was lifted (and the beeping completed) I pressed resume. The system rebooted and I was presented with the power loss, system start up (Creality community firmware splash screen) and then the resume print function. 
I tested it twice (same gcode file) with the same result.

**Comment by Sebazzz** [comment]
Unless someone else from @CR6Community/developers has time to look at this, I'Il receive a new CR-6 soon which I should be able to use to further troubleshoot this.

**Comment by Sebazzz** [comment]
[Creality v4.5.2 motherboard firmware-crealityv452-20201223-002158.zip](https://github.com/CR6Community/Marlin/files/5732408/firmware-crealityv452-20201223-002158.zip)
[Creality v4.5.3 motherboard firmware-crealityv453-20201223-002246.zip](https://github.com/CR6Community/Marlin/files/5732406/firmware-crealityv453-20201223-002246.zip)
[Touch screen firmware CR-6-touchscreen-2020-12-23.zip](https://github.com/CR6Community/Marlin/files/5732436/CR-6-touchscreen-2020-12-23.zip)

Can you please retry this with one of these firmware files, depending on the motherboard version you have. If you don't know or got a printer from November 2020 or earlier, you'Il most likely have the Creality v4.5.2 motherboard. 

Assuming we got it fixed I will close this issue now and consider it fixed. If it isn't fixed please provide:
- Logs captured via Pronterface/Octoprint/PuTTY with `M111 S247` entered for debug logging
- Pictures or a video as appropriate

Also, if it is fixed, I still would like to have a confirmation though😀
